// Regional document conventions: currency, date format, tax label and tax-ID format per locale.

export interface RegionTemplate {
  locale: string;
  intlLocale: string;
  currency: string;
  dateFormat: string;
  taxLabel: string;
  taxIdLabel: string;
  /** '#' = digit, 'A' = letter. */
  taxIdPattern: string;
  defaultTaxRate: number;
  /** Invented, clearly fictional bank names. Never use real banks: generated documents must not be usable as forgeries. */
  banks: string[];
}

export const REGIONS: Record<string, RegionTemplate> = {
  PK: { locale: 'PK', intlLocale: 'en-PK', currency: 'PKR', dateFormat: 'DD/MM/YYYY', taxLabel: 'GST', taxIdLabel: 'NTN', taxIdPattern: '#######-#', defaultTaxRate: 17, banks: ['Test Bank Pakistan (Demo)', 'Sample Savings Bank PK', 'Demo Commercial Bank Lahore'] },
  US: { locale: 'US', intlLocale: 'en-US', currency: 'USD', dateFormat: 'MM/DD/YYYY', taxLabel: 'Sales Tax', taxIdLabel: 'EIN', taxIdPattern: '##-#######', defaultTaxRate: 8, banks: ['Test Bank USA (Demo)', 'Sample Savings Bank US', 'Demo Trust Bank'] },
  GB: { locale: 'GB', intlLocale: 'en-GB', currency: 'GBP', dateFormat: 'DD/MM/YYYY', taxLabel: 'VAT', taxIdLabel: 'VAT No.', taxIdPattern: 'GB### #### ##', defaultTaxRate: 20, banks: ['Test Bank UK (Demo)', 'Sample Building Society', 'Demo Bank London'] },
  IN: { locale: 'IN', intlLocale: 'en-IN', currency: 'INR', dateFormat: 'DD/MM/YYYY', taxLabel: 'GST', taxIdLabel: 'GSTIN', taxIdPattern: '##AAAAA####A#Z#', defaultTaxRate: 18, banks: ['Test Bank India (Demo)', 'Sample Cooperative Bank', 'Demo Commercial Bank Mumbai'] },
  DE: { locale: 'DE', intlLocale: 'de-DE', currency: 'EUR', dateFormat: 'DD.MM.YYYY', taxLabel: 'MwSt', taxIdLabel: 'USt-IdNr.', taxIdPattern: 'DE#########', defaultTaxRate: 19, banks: ['Test Bank Deutschland (Demo)', 'Sample Sparkasse', 'Demo Volksbank'] },
  FR: { locale: 'FR', intlLocale: 'fr-FR', currency: 'EUR', dateFormat: 'DD/MM/YYYY', taxLabel: 'TVA', taxIdLabel: 'N° TVA', taxIdPattern: 'FR## #########', defaultTaxRate: 20, banks: ['Test Banque France (Demo)', 'Sample Banque', 'Demo Crédit Bank'] },
  CA: { locale: 'CA', intlLocale: 'en-CA', currency: 'CAD', dateFormat: 'YYYY-MM-DD', taxLabel: 'GST/HST', taxIdLabel: 'BN', taxIdPattern: '#########RT0001', defaultTaxRate: 13, banks: ['Test Bank Canada (Demo)', 'Sample Credit Union CA', 'Demo Trust Toronto'] },
  AU: { locale: 'AU', intlLocale: 'en-AU', currency: 'AUD', dateFormat: 'DD/MM/YYYY', taxLabel: 'GST', taxIdLabel: 'ABN', taxIdPattern: '## ### ### ###', defaultTaxRate: 10, banks: ['Test Bank Australia (Demo)', 'Sample Credit Union AU', 'Demo Savings Sydney'] },
};

/** Prefix for every generated identifier on documents (tax IDs, account numbers) so they can't pass as real. */
export const TEST_ID_PREFIX = 'TEST-';

/** Shown on every generated document (previews and PDFs). */
export const SYNTHETIC_WATERMARK = 'SYNTHETIC — FOR TESTING ONLY';
export const SYNTHETIC_FOOTER = 'Generated by Synthra. Not a real financial document.';

export function region(locale: string): RegionTemplate {
  return REGIONS[locale] ?? REGIONS.US;
}

/** Approximate units of each currency per 1 USD, used to scale realistic prices. */
export const USD_RATE: Record<string, number> = { USD: 1, PKR: 280, GBP: 0.79, INR: 83, EUR: 0.92, CAD: 1.36, AUD: 1.5 };

export function currencyRate(currency: string): number {
  return USD_RATE[currency] ?? 1;
}

/** Formats integer cents with Intl.NumberFormat (e.g. 172870 PKR → "Rs 1,728.70"). */
export function formatMoney(cents: number, currency: string, intlLocale: string): string {
  try {
    return new Intl.NumberFormat(intlLocale, { style: 'currency', currency }).format(cents / 100);
  } catch {
    return `${currency} ${(cents / 100).toFixed(2)}`;
  }
}

export const DAY_MS = 86_400_000;

/** 'YYYY-MM-DD' → UTC ms (NaN when invalid). */
export function isoToTs(iso: string): number {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  return m ? Date.UTC(+m[1], +m[2] - 1, +m[3]) : NaN;
}

export function tsToIso(ts: number): string {
  return new Date(ts).toISOString().slice(0, 10);
}
